name: Webtunnel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Install Deps
      run: |
        go install github.com/deepakkamesh/webtunnel/webtunnelserver@latest
        go install github.com/deepakkamesh/webtunnel/webtunnelcommon@latest
        go install github.com/golang/glog@latest
        go install github.com/google/gopacket@latest
        go install github.com/google/gopacket/layers@latest
        go install github.com/gorilla/websocket@latest
        go install github.com/songgao/water@latest
        go install github.com/golang/mock/gomock@latest

    - name: Build Server
      run: go build -v ./examples/server.go

    - name: Build Client
      run: go build -v ./examples/webtunclient.go ./examples/webtunclient_linux.go

    - name: Test Client
      run: go test -v ./webtunnelclient/

    - name: Test Server
      run: go test -v ./webtunnelserver/
